### ISSUE TITLE
list index out of range in latency plugin

### ISSUE THREAD

**Issue by bobrik** [rochaporto/collectd-ceph#33]
```
Jan 18 11:59:11 36s62 docker/9781622b6cd5[13999]: ceph: failed to get stats :: list index out of range :: Traceback (most recent call last):
Jan 18 11:59:11 36s62 docker/9781622b6cd5[13999]: File "/usr/lib/collectd/plugins/ceph/base.py", line 114, in read_callback
Jan 18 11:59:11 36s62 docker/9781622b6cd5[13999]: stats = self.get_stats()
Jan 18 11:59:11 36s62 docker/9781622b6cd5[13999]: File "/usr/lib/collectd/plugins/ceph/ceph_latency_plugin.py", line 67, in get_stats
Jan 18 11:59:11 36s62 docker/9781622b6cd5[13999]: data[ceph_cluster]['cluster']['stddev_latency'] = results[1]
Jan 18 11:59:11 36s62 docker/9781622b6cd5[13999]: IndexError: list index out of range
Jan 18 11:59:11 36s62 docker/9781622b6cd5[13999]:
Jan 18 11:59:11 36s62 docker/9781622b6cd5[13999]: Unhandled python exception in read callback: UnboundLocalError: local variable 'stats' referenced before assignment
Jan 18 11:59:11 36s62 docker/9781622b6cd5[13999]: read-function of plugin `python.ceph.ceph_latency_plugin' failed. Will suspend it for 120.000 seconds.
```

**Comment by ghost** [comment]
Do you have a "data" pool in your Ceph cluster? Line 54 in ceph_latency_plugin.py shows that the pool name of "data" is hardcoded.

**Comment by bobrik** [comment]
Yes, I do have it. It doesn't fail all the time too.

**Comment by ghost** [comment]
I changed line 54 to

`"timeout 30s rados --cluster "+ self.cluster +" -p "+ self.testpool +" bench 10 write -t 1 -b 65536 2>/dev/null | grep -i latency | awk '{print 1000*$3}'", shell=True)`

for testing, and since then it didn't fail anymore.

cheers
Mathias

**Comment by resyst-it** [comment]
ceph: failed to get stats :: list index out of range :: Traceback (most recent call last):#012  File "/opt/collectd/plugins/base.py", line 114, in read_callback#012    stats = self.get_stats()#012  File "/opt/collectd/plugins/ceph_latency_plugin.py", line 67, in get_stats#012    data[ceph_cluster]['cluster']['stddev_latency'] = results[1]#012IndexError: list index out of range

I have this error. I have no data pool. And i have changed the line 54 by this :+1: 
`timeout 30s rados --cluster "+ self.cluster +" -p "+ self.testpool +" bench 10 write -t 1 -b 65536 2>/dev/null | grep -i latency | awk '{print 1000*$3}'", shell=True)`

But i have this error ... Do you have an idea ?

Thank you.
