### ISSUE TITLE
Error on ceph_pg_plugin.py

### ISSUE THREAD

**Issue by ggkth901** [rochaporto/collectd-ceph#53]
hi i;m taehoon.
i deploying ceph clutser(Luminous).
So build monitoring system with graphite , grafana , collectd.

but i have Trouble below this.

-------/var/log/message ------------------------------------------------------------------------
Jun 11 10:09:42 ceph-mgr.cdngp.net collectd[57815]: ceph: failed to get stats :: 'fs_perf_stat' :: Traceback (most recent call last):#012  File "/usr/lib64/collectd/plugins/ceph/base.py", line 114, in read_callback#012    stats = self.get_stats()#012  File "/usr/lib64/collectd/plugins/ceph/ceph_pg_plugin.py", line 79, in get_stats#012    data[ceph_cluster][osd_id]['apply_latency_ms'] = osd['fs_perf_stat']['apply_latency_ms']#012KeyError: 'fs_perf_stat'

Jun 11 10:09:42 ceph-mgr.cdngp.net collectd[57815]: Unhandled python exception in read callback: UnboundLocalError: local variable 'stats' referenced before assignment

Jun 11 10:09:42 ceph-mgr.cdngp.net collectd[57815]: read-function of plugin `python.ceph_pg_plugin' failed. Will suspend it for 120.000 seconds.

Jun 11 10:09:43 ceph-mgr.cdngp.net collectd: dumped fsmap epoch 196

------------------------------------------------------------------------------------------------

somebody help me.. :-<

**Comment by calou46** [comment]
Hello sorry for my english, I have the same problem, i don't know how to transmit my workaround to the project's maintener. 
I made a workarround, for this: edit /usr/lib64/collectd/plugins/ceph/ceph_pg_plugin.py
change lines:
79  data[ceph_cluster][osd_id]['apply_latency_ms'] = osd['fs_perf_stat']['apply_latency_ms']
80  data[ceph_cluster][osd_id]['commit_latency_ms'] = osd['fs_perf_stat']['commit_latency_ms']
to:
79  data[ceph_cluster][osd_id]['apply_latency_ms'] = osd['perf_stat']['apply_latency_ms']
80  data[ceph_cluster][osd_id]['commit_latency_ms'] = osd['perf_stat']['commit_latency_ms']
Tested on luminous 12.2.7
